# Generated by Django 3.2.9 on 2021-12-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.CharField(default='https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.png', max_length=255),
            preserve_default=False,
        ),
    ]
