# Generated by Django 3.2.9 on 2021-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_url',
            field=models.CharField(default='https://i.ytimg.com/vi/zp4wYsGU78M/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBtW8tQCHIr4Fy3b7ig7yv7gdgJYw', max_length=255),
            preserve_default=False,
        ),
    ]
